---
title: "Regressions for paper_no MI"
author: "Ale Garcia"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(haven)
library(janitor)
library(knitr)
library(surveytoolbox)
library(sjPlot)
library(kableExtra)
library(psych)
library(sjmisc)
library(MVN)
library(stats)
library(AICcmodavg)
library(rsq)

theme_set(theme_minimal())
```


### The dataset ###

```{r}
d <- read_sav(here("outcomes paper/data_outcomes", "p_y_w1_for_analysesjan25_2.sav")) # 94 rows

# view_df(d)
```


```{r}
d1 <- d %>%
  select(school_id, family_id, participant_id, parent_eng_comf, youth_age, youth_gender, acadhwi_1, checkhwi_1, struct_1, knowschool_1, stratsbi_1, belong_1, endorse_1, ptrel_1, y_sch_eng, grades, selfeffic_1)


#convfut_1
# view_df(d1)
```


```{r}
d2 <- d1 %>%
  mutate(school_id = factor(school_id),
         parent_eng_comf = as.numeric(parent_eng_comf),
         youth_gender = factor(youth_gender),
         youth_age = as.numeric(youth_age))
```

### standardize (z-score)
```{r}
d3 <- d2 %>%
  mutate(across(where(is.numeric), ~ scale(.)[,1]))
d3
```


### School engagement - 10 rows deleted
With MI: 
checkhwi_1: beta = 0.28,  p = 0.01215964 (with MI significant)
ptrel_1: -0.27, 0.04000515
```{r, warning=FALSE}
fit_engage <- lm(y_sch_eng ~ parent_eng_comf + youth_age + youth_gender + acadhwi_1 + checkhwi_1 + struct_1 + knowschool_1 + stratsbi_1 + belong_1 + endorse_1 +  ptrel_1, d3)

summary(fit_engage) 

partial_r2 <- rsq.partial(fit_engage)
print(partial_r2)
```

### Youth-rep grades - 11 rows deleted
With MI:
youth_gender2: beta = -0.51, p = 0.02491487
```{r, warning=FALSE}
fit_grades <- lm(grades ~ parent_eng_comf + youth_age + youth_gender + acadhwi_1 + checkhwi_1 + struct_1 + knowschool_1 + stratsbi_1 + belong_1 + endorse_1 +  ptrel_1, d3)

summary(fit_grades) 

partial_r2 <- rsq.partial(fit_grades)
print(partial_r2)
```


### Parent self-efficacy - 10 rows deleted
With MI:
parent_eng_comf: beta = 0.15, p =  0.0247369655
belong_1: beta =  0.35, p = 0.0008911784
endorse_1: beta =   0.29,  p = 0.0043480189
```{r, warning=FALSE}
fit_efficacy <- lm(selfeffic_1 ~ parent_eng_comf + youth_age + youth_gender + acadhwi_1 + checkhwi_1 + struct_1 + knowschool_1 + stratsbi_1 + belong_1 + endorse_1 +  ptrel_1, d3)

summary(fit_efficacy) 

partial_r2 <- rsq.partial(fit_efficacy)
print(partial_r2)
```


#### Select variables of interest
```{r}
vars_of_interest <- d3[, c("parent_eng_comf", "youth_age", "acadhwi_1", "checkhwi_1", "struct_1", "knowschool_1", "stratsbi_1", "belong_1", "endorse_1", "ptrel_1", "y_sch_eng", "grades", "selfeffic_1")] # removed youth gender because is a factor
```


#### Convert to long format for ggplot
```{r}
long_data <- pivot_longer(vars_of_interest, cols = everything(), names_to = "Variable", values_to = "Value")
```


#### Plot histograms
```{r}
ggplot(long_data, aes(x = Value)) + 
  geom_histogram(bins = 30, fill = "skyblue", color = "black", alpha = 0.7) + 
  facet_wrap(~ Variable, scales = "free") +  # One plot per variable
  theme_minimal() + 
  labs(title = "Distribution of Variables")
```







