---
title: "parent_wave_3"
output: html_document
date: "2023-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(haven)
library(janitor)
library(knitr)
library(surveytoolbox)
library(sjPlot)
library(kableExtra)
library(psych)
library(sjmisc)
```

################## WAVE 3 ##################

# Loading the data & initial cleaning
```{r}
# wave 3 was separated in 2 different datasets.

p_w3_raw_a <- read_sav(here("nopublish", "7bb. Juntos Parent W3-SPAN_February 10, 2021_10.26.sav"))

p_w3_raw_a <- p_w3_raw_a %>% 
  arrange(ID_1_TEXT) %>% # ordering participants ids
  janitor::clean_names() %>% # cleaning names
  select(-id) %>% 
  rename(c("id" = "id_1_text"))

p_w3_raw_b <- read_sav(here("nopublish", "7bb. Juntos Parent W3-SPAN_February 10, 2021_10.27.sav"))

p_w3_raw_b <- p_w3_raw_b %>% 
  arrange(ID_1_TEXT) %>% # ordering participants ids
  janitor::clean_names() %>% # cleaning names
  select(-id) %>% 
  rename(c("id" = "id_1_text"))

p_w3_raw <- full_join(p_w3_raw_a, p_w3_raw_b) %>% 
  arrange(id) # 114 rows
```


# Checking incomplete rows & duplicated ids
```{r}
p_w3_raw %>%
  filter(finished == 0) # ids 310 (dad) & 613 (dad) had false starts

p_w3_raw2 <- p_w3_raw %>%
  select(-1:-8, -10:-17, -19, -20) %>% # selecting out columns with metadata
  filter(response_id != "R_2uUNENaFPEhYnLd") %>% # id 107 has -99 throughout
  filter(response_id != "R_2eOPgZuGKJkMCyd") %>% # id 310 has NA prob. false start
  filter(response_id != "R_3ffsDz6qZB2plqr") # id 613 has NA prob. false start

data.frame(table(p_w3_raw2$id)) # 23 ids have 2 or more instances each (ids 408 and 415 has 3 instances each)
```
# Fixing wrong condition assignment and school id
```{r}
# fixing wrong assignment
p_w3_clean <- p_w3_raw2 %>%
  mutate(school_id = str_sub(id, 1, 1),
         condition = case_when(
           school_id == "1" | school_id == "3" | school_id == "5" ~ "1",
           school_id == "2" | school_id == "4" | school_id == "6" ~ "2"
         )) %>%
  select(school_id, condition, everything()) %>%
  select(- school) # selecting out (i.e. deleting) original faulty school variable
```
# Adding value labels and making vars numeric 
```{r}
p_w3_clean_2 <- p_w3_clean %>%
  mutate(condition = as.numeric(condition),
         condition = set_vall(condition, c("control" = 1, "intervention" = 2)),
         school_id = as.numeric(school_id),
         school_id = set_vall(school_id, c("cascade" = 1, "prairie_mountain" = 2, "kelly" = 3, "ata" = 4, "briggs" = 5, "agnes_stewart" = 6)))
```
# Creating individual id variable
```{r}
p_w3_clean_3 <- p_w3_clean_2 %>%
  mutate(participant = set_vall(participant, c("mom" = 1, "dad" = 2, "tutor legal" = 3, "other, specify" = 4)),
         participant_id = paste0(id, "_", participant), .before = 5) %>% # new var as unique identifier
  rename(c("family_id" = "id")) %>%
  arrange(participant_id) 

view_df(p_w3_clean_3)
```
# renaming vars to correspond to value labels
```{r}
# item that asks about # of adults in home was spreaded out and had an unusual coding.
p_w3_clean_3 <- p_w3_clean_3 %>%
  rename(c("q211_1" = "q211_2"),
         c("q211_2" = "q211_99"),
         c("q211_3" = "q211_4"),
         c("q211_4" = "q211_5"),
         c("q211_5" = "q211_6"),
         c("q211_99" = "q211_7"),
         c("adults_home_text" = "q211_6_text"))
```

# checking duped ids
```{r}
# 111 rows of data

data.frame(table(p_w3_clean_3$participant_id)) # id 405 dupped -> 2 dads; id 408 dupped -> 2 dads; id 605 dupped -> 2 moms

p_w3_clean_3 %>%
  filter(family_id == 405) # 2 dads
# very similar responses but not identical. Differences on -99, NA, and zeros
# response_id: R_cXQAULkCQKs9ZWd says "imported" in dataset. virtually identical metadata info. 
# Logs info: two parent family (mom & dad) on w1, but no evidence of assessment completed for either on w2. 

p_w3_clean_3 %>%
  filter(participant_id == "408_2") # 2 dads
# very similar responses but not identical. Differences on -99, NA, and zeros
# # response_id: R_eWNINjAZviHsnzv says "imported" in dataset. 
# Logs info: two parent family (mom & dad) on w1 and w2 --> complete data.

p_w3_clean_3 %>%
  filter(family_id == 605) # 2 moms
# very similar responses but not identical. Differences on -99, NA, and zeros
# # response_id: R_0jEpFqwcLyP4yDX says "imported" in dataset.
# Logs info: one-parent family, a mom in wave 1 and 2. Complete data. 

# My overall conclusion: it appears that the duped "imported" cases are true duplicates. What differs is how Qualtrics coded non-responses: 0, NA, or -99. 

```

# Number of participants in Wave 3 (taking out duped cases 405, 408, 605)
```{r}

p_w3_clean_3 <- p_w3_clean_3 %>%
  filter(response_id != "R_cXQAULkCQKs9ZWd") %>% # id 405
  filter(response_id != "R_eWNINjAZviHsnzv") %>% # 408
  filter(response_id != "R_0jEpFqwcLyP4yDX") # id 605

# 108 total parent participants in w2, from which...

p_w3_clean_3 %>%
  filter(participant == 1) # 80 were moms

p_w3_clean_3 %>%
  filter(participant == 2) # 26 were dads

p_w3_clean_3 %>%
  filter(participant == 4) # 2 were "other" (1 stepmom (id 415), 1 grandmother (id 507)) 

unique(p_w3_clean_3$family_id) # 86 unique id values, thus 86 families in W2. 

data.frame(table(p_w3_clean_3$participant_id)) # 21 duplicated ids that match two-parent families in w1, 1 family (id 415) three-parent fam. 
```

```{r}
# p_w3_clean_3 %>%
#   haven::write_sav(here("nopublish", "all_parent_wave3.sav"))
```

